### ISSUE TITLE
Is Okta cached acess token expiration configurable

### ISSUE THREAD

**Issue by joshgch** [okta/okta-aws-cli#107]
The cached Okta access token only lasts for 1 hour. Is there any way to configure or extend this?

**Comment by monde** [comment]
@josephlbarnett requesting an an alternative `expires_in` value whe getting a device access token is not part of the Okta API. So that prevents us from having such a feature in okta/okta-aws-cli .

https://developer.okta.com/docs/reference/api/oidc/#request-parameters-5

You could open a support ticket asking for this https://support.okta.com/ but keep in mind it will go to the feature team in the Okta service that owns the token endpoint. It won't go to the Developer Community Products team that owns okta/okta-aws-cli
