### ISSUE TITLE
Cannot connect to AWS using identity engine

### ISSUE THREAD

**Issue by MaorPaz** [okta/okta-aws-cli#18]
All required fields are injected to CLI:

`okta-aws-cli -o "dev-***.okta.com" -c "***" -a "***"`

Prints out a URL to sign.

open the URL, 

Authenticated to Okta, 

Terminal output:
`Error: fetching SSO web token received API response "400 Bad Request"`

expected result : 

Should get credentials to my terminal.

Please help

**Comment by monde** [comment]
@MaorPaz my guess here is something isn't set up correctly between AWS AIM and your Okta AWS Federation app. As you point out, that error comes after you've authenticated in Okta so it seems like you have the correct client ids in your `-c` and `-a` settings otherwise you wouldn't have gotten this far. There are a lot of details in the wizard for setting everything up. We should get a set up video when we go GA, that would be helpful.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-545161

**Comment by MaorPaz** [comment]
> @MaorPaz my guess here is something isn't set up correctly between AWS AIM and your Okta AWS Federation app. As you point out, that error comes after you've authenticated in Okta so it seems like you have the correct client ids in your `-c` and `-a` settings otherwise you wouldn't have gotten this far. There are a lot of details in the wizard for setting everything up. We should get a set up video when we go GA, that would be helpful.

Thank you for your quick response,
we have managed to sort it out, you were guessing right,
the app on Okta didnt sets up correctly, vut the documentation in the main README, could and sould be me detailed.

thank you!!
