### ISSUE TITLE
v2.1.0 Hasn't been published via Chocolatey

### ISSUE THREAD

**Issue by officeSpacePirate** [okta/okta-aws-cli#186]
Looks like the latest release via Chocolatey is v2.0.1. It also looks like Chocolatey support is new, so perhaps that part hasn't been automated?

Anyway, the business I work for is looking to switch to this tool from saml2aws soon, so the Windows support is much appreciated in advance. Updated documentation would be helpful if you guys haven't already started on that.

**Comment by monde** [comment]
Thanks @officeSpacePirate I'm looking into this.

**Comment by laura-rodriguez** [comment]
Hi @officeSpacePirate,

Thanks for your request. You're right, releases via Chocolatey are new, and we're planning to automate releases soon. 
I'll file an internal ticket so the team can prioritize this request. We'll keep you posted here.

Thanks for your patience!

Internal Ref: OKTA-700629

**Comment by officeSpacePirate** [comment]
Thanks for the quick response. Obviously not an emergency, but looking forward to the new changes.

**Comment by lw-cchapin** [comment]
Will the amd64 builds resume soon?

**Comment by monde** [comment]
@lw-cchapin did you see the note in the [v2.0.1](https://github.com/okta/okta-aws-cli/releases/tag/v2.0.1) release ? We are no longer producing an amd64 build because binaries built from golang for amd64 are notable across the board for triggering various AVs. Can you get by with an i386 build? I don't have a Windows background, and thought any amd64 machine can run i386 binaries. please adjust my understanding. I want to get this right for you, but also having amd64 false positives is not a good confidence booster in general.

**Comment by emboss64** [comment]
Any updates on this one? Thanks!

**Comment by monde** [comment]
I'm in the process of writing a GH action for this publish a Chocolatey release when we do a GH release.

**Comment by monde** [comment]
ok v2.2.0 has been submitted via github action https://community.chocolatey.org/packages/okta-aws-cli#versionhistory
and all future releases will be automatically submitted.
Closing by #215
